// 01-programming-languages/frontend/vue/01-fundamentals/examples/App.vue
<template>
  <div class="app">
    <h1>{{ message }}</h1>
    
    <!-- Counter -->
    <div>
      <p>Count: {{ count }}</p>
      <button @click="increment">Increment</button>
      <button @click="decrement">Decrement</button>
    </div>

    <!-- List rendering -->
    <h2>Users</h2>
    <ul>
      <li v-for="user in users" :key="user.id">
        {{ user.name }} - {{ user.email }}
      </li>
    </ul>

    <!-- Conditional rendering -->
    <p v-if="users.length === 0">No users found</p>
    <p v-else>{{ users.length }} users loaded</p>

    <!-- Computed property -->
    <p>Double count: {{ doubleCount }}</p>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'

const message = ref('Hello Vue!')
const count = ref(0)
const users = ref([
  { id: 1, name: 'Alice', email: 'alice@example.com' },
  { id: 2, name: 'Bob', email: 'bob@example.com' }
])

const doubleCount = computed(() => count.value * 2)

const increment = () => count.value++
const decrement = () => count.value--
</script>

// 01-programming-languages/frontend/react/01-fundamentals/examples/App.tsx
import React, { useState, useEffect } from 'react';

// Types
interface User {
  id: number;
  name: string;
  email: string;
}

// Functional Component with Hooks
const App: React.FC = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [count, setCount] = useState<number>(0);

  useEffect(() => {
    // Simulate API call
    setTimeout(() => {
      setUsers([
        { id: 1, name: 'Alice', email: 'alice@example.com' },
        { id: 2, name: 'Bob', email: 'bob@example.com' },
      ]);
      setLoading(false);
    }, 1000);
  }, []);

  if (loading) {
    return <div>Loading...</div>;
  }

  return (
    <div className="App">
      <h1>React Fundamentals</h1>
      
      {/* Counter with useState */}
      <div>
        <p>Count: {count}</p>
        <button onClick={() => setCount(count + 1)}>Increment</button>
        <button onClick={() => setCount(count - 1)}>Decrement</button>
      </div>

      {/* List rendering */}
      <h2>Users</h2>
      <ul>
        {users.map((user) => (
          <li key={user.id}>
            {user.name} - {user.email}
          </li>
        ))}
      </ul>

      {/* Conditional rendering */}
      {users.length === 0 ? (
        <p>No users found</p>
      ) : (
        <p>{users.length} users loaded</p>
      )}
    </div>
  );
};

export default App;
